# Generated by Django 2.1.5 on 2019-02-06 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Valor Unico (R.A)', primary_key=True, serialize=False)),
                ('aluno', models.CharField(max_length=150)),
                ('nota1', models.IntegerField()),
                ('nota2', models.IntegerField()),
                ('nota3', models.IntegerField()),
                ('media', models.IntegerField()),
            ],
        ),
    ]
